---
- hosts: localhost

  connection:   local
  gather_facts: no

  vars:
    workspace:    "{{playbook_dir}}/.secrets"
    vault_file:   "ansible-learning.vault"
    vault_string: "elbisna"

  tasks:
    - name: create secrets space
      file: path="{{workspace}}" state="directory" mode=0700

    - name: generate repository secrets
      copy: dest="{{workspace}}/{{vault_file}}" content="{{vault_string}}" mode=0600
