---
- hosts: localhost

  connection:   local
  gather_facts: no

  vars:
    workspace:   "{{playbook_dir}}/tmp/shell"
    test_file:   "test.txt"
    test_string: "this is not a test"

  tasks:
    - name: create workspace
      shell: >
        mkdir -p {{workspace}}

    - name: touch file
      shell: >
        touch {{workspace}}/file.touch

    - name: add content to file
      shell: >
        echo "{{test_string}}"
        > {{workspace}}/{{test_file}}

    - name: read file content
      shell: >
        cat {{workspace}}/{{test_file}}
      changed_when: false
      register: shell_test_string

    - name: display file content
      debug: msg="{{test_file}} contains '{{shell_test_string.stdout}}'"
