---
- name: foo secrets
  hosts: localhost

  connection:   local
  gather_facts: no

  vars_files:
    - vars/secrets.yml

  vars:
    workspace:    "{{playbook_dir}}/vars"
    vault_file:   "secrets.yml"

  tasks:
    - name: read secrets file contents
      shell: >
        cat {{workspace}}/{{vault_file}}
      changed_when: false
      register: shell_vault_string

    - name: display encrypted secrets
      debug: msg="{{vault_file}} contains '{{shell_vault_string.stdout}}'"

    - name: display message (vault-unencrypted)
      debug: var=message
